name: Detection Real Partners

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-partners:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get changed files
      id: changed-files
      run: |
        git diff --name-only HEAD^ HEAD | grep '\.py$' > changed_files.txt

    - name: Read changed files
      id: read-changed-files
      run: |
        cat changed_files.txt

    - name: Check for specific partner names and URLs in changed files
      id: check-partners-files
      run: |
        set -e
        PARTNER_NAMES="A B C D E"
        ERROR_FOUND=0

        while IFS= read -r FILE; do
          if [ -f "$FILE" ]; then
            # Check for SettingKeys.PARTNER_NAME
            if grep -q 'settings.env_variables\[SettingKeys.PARTNER_NAME\]' "$FILE"; then
              PARTNER_NAME=$(grep 'settings.env_variables\[SettingKeys.PARTNER_NAME\]' "$FILE" | sed -n 's/.*settings.env_variables\[SettingKeys.PARTNER_NAME\] = "\(.*\)".*/\1/p')
              if [[ " $PARTNER_NAMES " =~ " $PARTNER_NAME " ]]; then
                echo "File $FILE has a valid partner name: $PARTNER_NAME"
              else
                echo "File $FILE has an invalid partner name: $PARTNER_NAME"
                ERROR_FOUND=1
              fi
            else
              echo "File $FILE does not contain the partner name setting."
            fi

            # Check for partner_url
            if grep -q 'partner_url = "https://[A-Za-z0-9\-\.]*\.inone\.insidethekube\.com/"' "$FILE"; then
              PARTNER_URL=$(grep 'partner_url = "https://[A-Za-z0-9\-\.]*\.inone\.insidethekube\.com/"' "$FILE" | sed -n 's/.*partner_url = "https:\/\/\([A-Za-z0-9\-\.]*\)\.inone\.insidethekube\.com\/".*/\1/p')
              if [[ " $PARTNER_NAMES " =~ " $PARTNER_URL " ]]; then
                echo "File $FILE has a valid partner URL: $PARTNER_URL"
              else
                echo "File $FILE has an invalid partner URL: $PARTNER_URL"
                ERROR_FOUND=1
              fi
            else
              echo "File $FILE does not contain the partner URL setting."
            fi
          fi
        done < changed_files.txt

        if [ $ERROR_FOUND -eq 1 ]; then
          echo "One or more files contain invalid partner names or URLs."
          exit 1
        else
          echo "All test files are valid."
        fi

















