name: Test File Validation

on:
  pull_request:
    paths:
      - '**/tests/**'

jobs:
  validate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find test files
      run: |
        mkdir -p test_files
        find . -type f -path "*/tests/*" -name "*.py" -exec cp {} test_files/ \;

    - name: Check test files for partner names
      run: |
        set -e
        PARTNER_NAMES="A B C D E"
        ERROR_FOUND=0

        for FILE in test_files/*.py; do
          if grep -q 'settings.env_variables\[SettingKeys.PARTNER_NAME\]' "$FILE"; then
            PARTNER_NAME=$(grep 'settings.env_variables\[SettingKeys.PARTNER_NAME\]' "$FILE" | sed 's/.*settings.env_variables\[SettingKeys.PARTNER_NAME\] = "\(.*\)".*/\1/')
            if [[ "$PARTNER_NAMES" =~ "$PARTNER_NAME" ]]; then
              echo "File $FILE has a valid partner name: $PARTNER_NAME"
            else
              echo "File $FILE has an invalid partner name: $PARTNER_NAME"
              ERROR_FOUND=1
            fi
          else
            echo "File $FILE does not contain the partner name setting."
          fi
        done

        if [ $ERROR_FOUND -eq 1 ]; then
          echo "One or more files contain invalid partner names."
          exit 1
        fi

    - name: Success
      if: success()
      run: echo "All test files are valid."





